<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <OutputPath>..\bin\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <OutputPath>..\bin\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="..\GlobalAssemblyInfo.cs">
            <Link>Properties\GlobalAssemblyInfo.cs</Link>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\IssueReporting\SyncVPN.IssueReporting.Contracts\SyncVPN.IssueReporting.Contracts.csproj" />
        <ProjectReference Include="..\OperatingSystems\NameResolutionPolicyTable\SyncVPN.OperatingSystems.NRPT.Contracts\SyncVPN.OperatingSystems.NRPT.Contracts.csproj" />
        <ProjectReference Include="..\OperatingSystems\Network\SyncVPN.OperatingSystems.Network.Contracts\SyncVPN.OperatingSystems.Network.Contracts.csproj" />
        <ProjectReference Include="..\OperatingSystems\Processes\SyncVPN.OperatingSystems.Processes.Contracts\SyncVPN.OperatingSystems.Processes.Contracts.csproj" />
        <ProjectReference Include="..\OperatingSystems\Ras\SyncVPN.OperatingSystems.Ras.Contracts\SyncVPN.OperatingSystems.Ras.Contracts.csproj" />
        <ProjectReference Include="..\OperatingSystems\Ras\SyncVPN.OperatingSystems.Ras\SyncVPN.OperatingSystems.Ras.csproj" />
        <ProjectReference Include="..\OperatingSystems\Services\SyncVPN.OperatingSystems.Services.Contracts\SyncVPN.OperatingSystems.Services.Contracts.csproj" />
        <ProjectReference Include="..\SyncVPN.Common.Legacy\SyncVPN.Common.Legacy.csproj" />
        <ProjectReference Include="..\SyncVPN.WireGuardDriver\SyncVPN.WireGuardDriver.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Autofac" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="System.Collections.Immutable" />
        <PackageReference Include="System.Formats.Asn1" />
        <PackageReference Include="System.Management" />
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
        <PackageReference Include="System.Text.Json" />
    </ItemGroup>
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
</Project>
