<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<PreserveCompilationContext>true</PreserveCompilationContext>
		<OutputType>Library</OutputType>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<OutputPath>..\..\bin\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="..\..\GlobalAssemblyInfo.cs">
			<Link>Properties\GlobalAssemblyInfo.cs</Link>
		</Compile>
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\Common\SyncVPN.Common.Core\SyncVPN.Common.Core.csproj" />
	  <ProjectReference Include="..\..\Configurations\SyncVPN.Configurations.Contracts\SyncVPN.Configurations.Contracts.csproj" />
	  <ProjectReference Include="..\..\Logging\SyncVPN.Logging.Contracts\SyncVPN.Logging.Contracts.csproj" />
	  <ProjectReference Include="..\SyncVPN.IPv6.Contracts\SyncVPN.IPv6.Contracts.csproj" />
	</ItemGroup>

</Project>