<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <OutputPath>..\..\..\bin</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Management" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\..\GlobalAssemblyInfo.cs" Link="Properties\GlobalAssemblyInfo.cs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Logging\SyncVPN.Logging.Contracts\SyncVPN.Logging.Contracts.csproj" />
        <ProjectReference Include="..\SyncVPN.OperatingSystems.Antiviruses.Contracts\SyncVPN.OperatingSystems.Antiviruses.Contracts.csproj" />
    </ItemGroup>

</Project>