<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<PreserveCompilationContext>true</PreserveCompilationContext>
		<OutputType>Library</OutputType>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<OutputPath>..\..\bin\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Common\SyncVPN.Common.Core\SyncVPN.Common.Core.csproj" />
	</ItemGroup>

</Project>