<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputPath>..\..\..\..\bin</OutputPath>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="System.Formats.Asn1" />
      <PackageReference Include="System.Text.Json" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\..\..\Api\SyncVPN.Api.Contracts\SyncVPN.Api.Contracts.csproj" />
      <ProjectReference Include="..\..\..\..\Common\SyncVPN.Common.Core\SyncVPN.Common.Core.csproj" />
      <ProjectReference Include="..\..\..\..\EntityMapping\SyncVPN.EntityMapping.Contracts\SyncVPN.EntityMapping.Contracts.csproj" />
      <ProjectReference Include="..\..\..\..\Logging\SyncVPN.Logging.Contracts\SyncVPN.Logging.Contracts.csproj" />
      <ProjectReference Include="..\SyncVPN.Client.Logic.Announcements.Contracts\SyncVPN.Client.Logic.Announcements.Contracts.csproj" />
    </ItemGroup>
</Project>