namespace SyncVPN.OperatingSystems.WebAuthn;

public static partial class PInvoke
{
    public const uint WEBAUTHN_API_VERSION_1 = 1U;

    public const uint WEBAUTHN_API_VERSION_2 = 2U;

    public const uint WEBAUTHN_API_VERSION_3 = 3U;

    public const uint WEBAUTHN_API_VERSION_4 = 4U;

    public const uint WEBAUTHN_API_VERSION_5 = 5U;

    public const uint WEBAUTHN_API_VERSION_6 = 6U;

    public const uint WEBAUTHN_API_VERSION_7 = 7U;

    public const uint WEBAUTHN_API_CURRENT_VERSION = 7U;

    public const uint WEBAUTHN_MAX_USER_ID_LENGTH = 64U;

    public const string WEBAUTHN_HASH_ALGORITHM_SHA_256 = "SHA-256";

    public const string WEBAUTHN_HASH_ALGORITHM_SHA_384 = "SHA-384";

    public const string WEBAUTHN_HASH_ALGORITHM_SHA_512 = "SHA-512";

    public const uint WEBAUTHN_AUTHENTICATOR_HMAC_SECRET_VALUES_FLAG = 1048576U;

    public const uint WEBAUTHN_ASSERTION_VERSION_1 = 1U;

    public const uint WEBAUTHN_ASSERTION_VERSION_2 = 2U;

    public const uint WEBAUTHN_ASSERTION_VERSION_3 = 3U;

    public const uint WEBAUTHN_ASSERTION_VERSION_4 = 4U;

    public const uint WEBAUTHN_ASSERTION_VERSION_5 = 5U;

    public const uint WEBAUTHN_ASSERTION_CURRENT_VERSION = 5U;

    public const uint WEBAUTHN_ATTESTATION_DECODE_NONE = 0U;

    public const uint WEBAUTHN_ATTESTATION_DECODE_COMMON = 1U;

    public const uint WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_ANY = 0U;

    public const uint WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_NONE = 1U;

    public const uint WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT = 2U;

    public const uint WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT = 3U;

    public const uint WEBAUTHN_AUTHENTICATOR_ATTACHMENT_ANY = 0U;

    public const uint WEBAUTHN_AUTHENTICATOR_ATTACHMENT_PLATFORM = 1U;

    public const uint WEBAUTHN_AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM = 2U;

    public const uint WEBAUTHN_AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM_U2F_V2 = 3U;

    public const uint WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_1 = 1U;

    public const uint WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_2 = 2U;

    public const uint WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_3 = 3U;

    public const uint WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_4 = 4U;

    public const uint WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_5 = 5U;

    public const uint WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_6 = 6U;

    public const uint WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_7 = 7U;

    public const uint WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_CURRENT_VERSION = 7U;

    public const uint WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_1 = 1U;

    public const uint WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_2 = 2U;

    public const uint WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_3 = 3U;

    public const uint WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_4 = 4U;

    public const uint WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_5 = 5U;

    public const uint WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_6 = 6U;

    public const uint WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_7 = 7U;

    public const uint WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_CURRENT_VERSION = 7U;

    public const int WEBAUTHN_COSE_ALGORITHM_ECDSA_P256_WITH_SHA256 = -7;

    public const int WEBAUTHN_COSE_ALGORITHM_ECDSA_P384_WITH_SHA384 = -35;

    public const int WEBAUTHN_COSE_ALGORITHM_ECDSA_P521_WITH_SHA512 = -36;

    public const int WEBAUTHN_COSE_ALGORITHM_RSASSA_PKCS1_V1_5_WITH_SHA256 = -257;

    public const int WEBAUTHN_COSE_ALGORITHM_RSASSA_PKCS1_V1_5_WITH_SHA384 = -258;

    public const int WEBAUTHN_COSE_ALGORITHM_RSASSA_PKCS1_V1_5_WITH_SHA512 = -259;

    public const int WEBAUTHN_COSE_ALGORITHM_RSA_PSS_WITH_SHA256 = -37;

    public const int WEBAUTHN_COSE_ALGORITHM_RSA_PSS_WITH_SHA384 = -38;

    public const int WEBAUTHN_COSE_ALGORITHM_RSA_PSS_WITH_SHA512 = -39;

    public const uint WEBAUTHN_COMMON_ATTESTATION_CURRENT_VERSION = 1U;

    public const uint WEBAUTHN_USER_VERIFICATION_REQUIREMENT_ANY = 0U;

    public const uint WEBAUTHN_USER_VERIFICATION_REQUIREMENT_REQUIRED = 1U;

    public const uint WEBAUTHN_USER_VERIFICATION_REQUIREMENT_PREFERRED = 2U;

    public const uint WEBAUTHN_USER_VERIFICATION_REQUIREMENT_DISCOURAGED = 3U;

    public const uint WEBAUTHN_USER_VERIFICATION_ANY = 0U;

    public const uint WEBAUTHN_USER_VERIFICATION_OPTIONAL = 1U;

    public const uint WEBAUTHN_USER_VERIFICATION_OPTIONAL_WITH_CREDENTIAL_ID_LIST = 2U;

    public const uint WEBAUTHN_USER_VERIFICATION_REQUIRED = 3U;

    public const uint WEBAUTHN_USER_ENTITY_INFORMATION_CURRENT_VERSION = 1U;

    public const uint WEBAUTHN_LARGE_BLOB_SUPPORT_NONE = 0U;

    public const uint WEBAUTHN_LARGE_BLOB_SUPPORT_REQUIRED = 1U;

    public const uint WEBAUTHN_LARGE_BLOB_SUPPORT_PREFERRED = 2U;

    public const uint CTAPCBOR_HYBRID_STORAGE_LINKED_DATA_VERSION_1 = 1U;

    public const uint CTAPCBOR_HYBRID_STORAGE_LINKED_DATA_CURRENT_VERSION = 1U;

    public const uint WEBAUTHN_CREDENTIAL_DETAILS_VERSION_1 = 1U;

    public const uint WEBAUTHN_CREDENTIAL_DETAILS_VERSION_2 = 2U;

    public const uint WEBAUTHN_CREDENTIAL_DETAILS_CURRENT_VERSION = 2U;

    public const uint WEBAUTHN_CLIENT_DATA_CURRENT_VERSION = 1U;

    public const uint WEBAUTHN_COSE_CREDENTIAL_PARAMETER_CURRENT_VERSION = 1U;

    public const uint WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_1 = 1U;

    public const uint WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_2 = 2U;

    public const uint WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_3 = 3U;

    public const uint WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_4 = 4U;

    public const uint WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_5 = 5U;

    public const uint WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_6 = 6U;

    public const uint WEBAUTHN_CREDENTIAL_ATTESTATION_CURRENT_VERSION = 6U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_OPERATION_NONE = 0U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_OPERATION_GET = 1U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_OPERATION_SET = 2U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_OPERATION_DELETE = 3U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_STATUS_NONE = 0U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_STATUS_SUCCESS = 1U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_STATUS_NOT_SUPPORTED = 2U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_STATUS_INVALID_DATA = 3U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_STATUS_INVALID_PARAMETER = 4U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_STATUS_NOT_FOUND = 5U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_STATUS_MULTIPLE_CREDENTIALS = 6U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_STATUS_LACK_OF_SPACE = 7U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_STATUS_PLATFORM_ERROR = 8U;

    public const uint WEBAUTHN_CRED_LARGE_BLOB_STATUS_AUTHENTICATOR_ERROR = 9U;

    public const uint WEBAUTHN_CTAP_TRANSPORT_USB = 1U;

    public const uint WEBAUTHN_CTAP_TRANSPORT_NFC = 2U;

    public const uint WEBAUTHN_CTAP_TRANSPORT_BLE = 4U;

    public const uint WEBAUTHN_CTAP_TRANSPORT_TEST = 8U;

    public const uint WEBAUTHN_CTAP_TRANSPORT_INTERNAL = 16U;

    public const uint WEBAUTHN_CTAP_TRANSPORT_HYBRID = 32U;

    public const uint WEBAUTHN_CTAP_TRANSPORT_FLAGS_MASK = 63U;

    public const uint WEBAUTHN_CREDENTIAL_EX_CURRENT_VERSION = 1U;

    public const uint WEBAUTHN_CREDENTIAL_CURRENT_VERSION = 1U;

    public const uint WEBAUTHN_ENTERPRISE_ATTESTATION_NONE = 0U;

    public const uint WEBAUTHN_ENTERPRISE_ATTESTATION_VENDOR_FACILITATED = 1U;

    public const uint WEBAUTHN_ENTERPRISE_ATTESTATION_PLATFORM_MANAGED = 2U;

    public const uint WEBAUTHN_RP_ENTITY_INFORMATION_CURRENT_VERSION = 1U;

    public const uint WEBAUTHN_GET_CREDENTIALS_OPTIONS_VERSION_1 = 1U;

    public const uint WEBAUTHN_GET_CREDENTIALS_OPTIONS_CURRENT_VERSION = 1U;

    public const uint WEBAUTHN_CTAP_ONE_HMAC_SECRET_LENGTH = 32U;

    public const string WEBAUTHN_CREDENTIAL_TYPE_PUBLIC_KEY = "public-key";

    public const string WEBAUTHN_EXTENSIONS_IDENTIFIER_HMAC_SECRET = "hmac-secret";

    public const string WEBAUTHN_EXTENSIONS_IDENTIFIER_CRED_PROTECT = "credProtect";

    public const string WEBAUTHN_EXTENSIONS_IDENTIFIER_CRED_BLOB = "credBlob";

    public const string WEBAUTHN_EXTENSIONS_IDENTIFIER_MIN_PIN_LENGTH = "minPinLength";
}
